services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: kamadvice
      POSTGRES_USER: kamadvice
      POSTGRES_PASSWORD: kamadvice
    ports:
      - "5432:5432"
    volumes:
      - kamadvice-postgres-data:/var/lib/postgresql/data

volumes:
  kamadvice-postgres-data:
